version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /packages/go
    schedule:
      interval: weekly
  - package-ecosystem: maven
    directory: /packages/java
    schedule:
      interval: weekly
  - package-ecosystem: composer
    directory: /packages/laravel
    schedule:
      interval: weekly
